---

# PiCamera options.
picamera: 
    # Where to store taken pictures.
    photo_directory: "/home/pi/pimaton_pictures"
    number_of_pictures_to_take: 6
    time_before_first_picture: 2
    time_between_pictures: 1
    # Prefix for the name of the taken pictures.
    picture_prefix_name: "test_pimaton"

# Pimaton global options.
pimaton: 
    time_between_loop: 2
    # UI mode, can be tui (Text user interface) or GUI (graphical user interface)
    # For the GUI to work, you need X and a desktop manager.
    # Only tui mode is available for now.
    ui_mode: 'tui'

# Image options.
image:
    print_pic:
        # Prefix for the generated image.
        generated_prefix_name: "pimaton"
        # Path for the template jpg to use if any. 
        # Put empty string if no template.
        template: "./assets/templates/Blank.tpl.jpg"
        # Directory where are stored the generated pictures.
        output_dir: "/home/pi/pimaton_pictures"
        # Width and Height of the generated image.
        width: 1241
        height: 1754
        # Columns and Rows for the generated image.
        rows: 3
        cols: 2

    # Thumbnails size.
    thumbnails: 
        width: 560
        height: 496

input:
    # Type can be Keyboard or GPIO.
    # Keyboard type means waiting for any key to be pressed.
    type: "keyboard"
    # Options depends on type.
    # Type: Keyboard doesn't have any options as it just wait for any key to be pressed.
    # options:

print:
    # If pimaton should try to print the generated picture.
    enabled: true
    # The rest of the options are only needed if pimaton[enable_print] is True.
    user: 'pi'
    printer_key: 0
    app_name: 'Pimaton'
    # Options to path to pycups printFile method
    options:
        fit-to-page: 'True'
        # copies: 2
